
import java.awt.event.ActionEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author John
 */
public class My_Lab4_Frame extends java.awt.Frame implements java.awt.event.ActionListener
{
   private PicFig picfig;
   private StickFig stickfig;
   private javax.swing.Timer moveTimer = new javax.swing.Timer(500, this);
   
   /**
    Creates new form My_Lab4_Frame
    */
   public My_Lab4_Frame()
   {
      initComponents();
      setSize(550, 450);
      picfig = new PicFig(figPanel);
      stickfig = new StickFig(figPanel);
      moveTimer.start();
      figPanel.requestFocus();
   }

   @Override
   public void actionPerformed(ActionEvent ae)
   {
      picfig.hide();
      picfig.move();
      picfig.draw();
      stickfig.hide();
      stickfig.move();
      stickfig.draw();
      try
      {
         if (picfig.collidedWith(stickfig))
         {
            java.io.File soundFile = new java.io.File(
                  "C:\\Windows\\Media\\chord.wav");
            javax.sound.sampled.AudioInputStream audioIn =
                  javax.sound.sampled.AudioSystem.getAudioInputStream(
                  soundFile);
            javax.sound.sampled.Clip clip =
                  javax.sound.sampled.AudioSystem.getClip();

            clip.open(audioIn);
            clip.start();
         }
      }
      catch (Exception ex)
      {
         System.out.println(ex);
      }

   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      figPanel = new java.awt.Panel();
      speedLabel = new java.awt.Label();
      faster = new java.awt.Button();
      slower = new java.awt.Button();
      reset = new java.awt.Button();

      setMinimumSize(new java.awt.Dimension(500, 500));
      setTitle("My Lab4 Frame");
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      figPanel.setBackground(new java.awt.Color(192, 192, 192));
      figPanel.setName("figPanel"); // NOI18N
      figPanel.addKeyListener(new java.awt.event.KeyAdapter()
      {
         public void keyPressed(java.awt.event.KeyEvent evt)
         {
            myKeyAdapter(evt);
         }
      });
      add(figPanel);
      figPanel.setBounds(0, 0, 400, 210);

      speedLabel.setName("speedLabel"); // NOI18N
      speedLabel.setText("Speed Controls");
      add(speedLabel);
      speedLabel.setBounds(0, 210, 90, 20);

      faster.setLabel("Increase");
      faster.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            fasterHandler(evt);
         }
      });
      add(faster);
      faster.setBounds(0, 230, 64, 24);

      slower.setLabel("Decrease");
      slower.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            slowerHandler(evt);
         }
      });
      add(slower);
      slower.setBounds(60, 230, 70, 24);

      reset.setLabel("Reset");
      reset.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            resetHandler(evt);
         }
      });
      add(reset);
      reset.setBounds(120, 230, 49, 24);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   private void myKeyAdapter(java.awt.event.KeyEvent evt)//GEN-FIRST:event_myKeyAdapter
   {//GEN-HEADEREND:event_myKeyAdapter
      stickfig.hide();
      if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN)
      {
         stickfig.move(0, 10);
      }
      else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP)
      {
         stickfig.move(0, -10);
      }
      else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT)
      {
         stickfig.move(-10, 0);
      }
      else if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT)
      {
         stickfig.move(10, 0);
      }
      stickfig.draw();
      picfig.draw();
   }//GEN-LAST:event_myKeyAdapter

   private void fasterHandler(java.awt.event.MouseEvent evt)//GEN-FIRST:event_fasterHandler
   {//GEN-HEADEREND:event_fasterHandler
      int t = moveTimer.getDelay();
      moveTimer.stop();
      moveTimer.setDelay(t - 100);
      moveTimer.start();
   }//GEN-LAST:event_fasterHandler

   private void slowerHandler(java.awt.event.MouseEvent evt)//GEN-FIRST:event_slowerHandler
   {//GEN-HEADEREND:event_slowerHandler
      int t = moveTimer.getDelay();
      moveTimer.stop();
      moveTimer.setDelay(t + 100);
      moveTimer.start();
   }//GEN-LAST:event_slowerHandler

   private void resetHandler(java.awt.event.MouseEvent evt)//GEN-FIRST:event_resetHandler
   {//GEN-HEADEREND:event_resetHandler
      moveTimer.stop();
      moveTimer.setDelay(500);
      moveTimer.start();
   }//GEN-LAST:event_resetHandler

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new My_Lab4_Frame().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button faster;
   private java.awt.Panel figPanel;
   private java.awt.Button reset;
   private java.awt.Button slower;
   private java.awt.Label speedLabel;
   // End of variables declaration//GEN-END:variables
}
